In [1]:
print("Hello World!")

Hello World!


In [2]:
myVar = "Hello World"

In [3]:
print(myVar)

Hello World


In [4]:
age = 44
height = 1.3


In [5]:
print(age)

44


In [6]:
print(height)

1.3


### Strings

In [7]:
introduction = "Hi, My name is Ifeoluwa."
print(introduction)

Hi, My name is Ifeoluwa.


In [8]:
Age = "22"
print(Age)

22


In [9]:
type(introduction)

str

In [10]:
type(age)

int

In [11]:
type(height)

float

In [12]:
type(Age)

str

In [14]:
str1 = 'This is my friend\'s car'
print(str1)

This is my frined's car


In [25]:
name = 'Mark'
surname = 'John'
age_mark = 44
new_year = '1'

print(name + ' ' + surname) #Concatenation

Mark John


In [26]:
print('Mark is ' + str(age_mark) + ' years old.') #Casting int to str

Mark is 44 years old.


In [28]:
age_mark + int(new_year) #Casting to str to int

45

In [29]:
print('Mark is {} years old.'.format(age_mark)) #Casting int to str

Mark is 44 years old.


In [30]:
height = 1.7
print('Mark is {a} years old and he is {h} meters tall.'.format(a=age_mark, h=height)) #Casting int to str

Mark is 44 years old and he is 1.7 meters tall.


### Numbers

In [31]:
num1 = 23
num2 = 2.4
num3 = 44

In [32]:
num1/num2

9.583333333333334

In [33]:
num1 * num2

55.199999999999996

In [34]:
num1 ** 2

529

In [35]:
num3 % 3

2

In [36]:
25 ** 0.5

5.0

In [37]:
type(25 ** 0.5)

float

In [87]:
num1 > num2

True

In [89]:
num2 > num1

False

In [92]:
num2 != num1 #Not equals to

True

In [93]:
num2 == num1

False

In [94]:
num2 >= num1

False

### List

In [38]:
list1 = [12, 'Hello', 4.3, ['Ife', 6.6]]

In [39]:
list1.append('new')

In [40]:
list1

[12, 'Hello', 4.3, ['Ife', 6.6], 'new']

In [42]:
list1[3]

['Ife', 6.6]

In [43]:
list1[-1]

'new'

In [45]:
list1[3][0]

'Ife'

In [46]:
list1[0] = 13
list1

[13, 'Hello', 4.3, ['Ife', 6.6], 'new']

In [47]:
len(list1)

5

In [48]:
nest = [1,2,3,[4,5,['target']]]

In [50]:
nest[-2]

3

In [52]:
nest[3][2][0]

'target'

In [53]:
nest[-1][-1][-1]

'target'

In [61]:
my_list = [1,3,4,5,6,8,34]
my_list[1:4] #Slicing a list

[3, 4, 5]

In [63]:
my_list[:3]

[1, 3, 4]

In [64]:
my_list[:-4]

[1, 3, 4]

### Dictionaries

In [55]:
# Dictionaries are denoted by key:value pairs
d = {'Name' : 'Ife', 
     'Age': 11, 
     122: 233,
    'scores': [33, 24, 4.4]}

In [81]:
d[122]

233

In [56]:
d['Age']

11

In [58]:
d['scores'][1]

24

In [65]:
dict2 = {
    'name': 'Matt',
    'age': 45,
    'kids': ['Esther', 'Rose'],
    'foods': ['burger', 'beans'],
    'movies': {
        'action': 'Terminator',
        'romance': 'Titanic'
    }
}

In [67]:
dict2['kids'][1]

'Rose'

In [71]:
dict2['movies']['romance']

'Titanic'

In [72]:
dict2

{'name': 'Matt',
 'age': 45,
 'kids': ['Esther', 'Rose'],
 'foods': ['burger', 'beans'],
 'movies': {'action': 'Terminator', 'romance': 'Titanic'}}

In [73]:
dict2['height'] = 1.8

In [74]:
dict2

{'name': 'Matt',
 'age': 45,
 'kids': ['Esther', 'Rose'],
 'foods': ['burger', 'beans'],
 'movies': {'action': 'Terminator', 'romance': 'Titanic'},
 'height': 1.8}

In [77]:
#Updating/changing  a dictionary value
dict2['movies']['action'] = 'Mission Impossible' 

In [78]:
dict2

{'name': 'Matt',
 'age': 45,
 'kids': ['Esther', 'Rose'],
 'foods': ['burger', 'beans'],
 'movies': {'action': 'Mission Impossible', 'romance': 'Titanic'},
 'height': 1.8}

In [79]:
del dict2['height']

In [80]:
dict2

{'name': 'Matt',
 'age': 45,
 'kids': ['Esther', 'Rose'],
 'foods': ['burger', 'beans'],
 'movies': {'action': 'Mission Impossible', 'romance': 'Titanic'}}

### Booleans

In [82]:
myboo1 = True
mybool2 = False

In [83]:
type(myboo1)

bool

### Tuples

In [95]:
mytuple = ('hi', 44, 9.8)

In [96]:
mytuple[0]

'hi'

In [97]:
mytuple[0] = 3

TypeError: 'tuple' object does not support item assignment

In [98]:
mytuple

('hi', 44, 9.8)

In [101]:
fruits = ("apple", "banana", "cherry")

green, yellow, red = fruits #Unpacking a tuple

In [102]:
green

'apple'

### Sets

In [108]:
myset = {"apple",56, "banana", "cherry", "apple"}

In [109]:
myset

{56, 'apple', 'banana', 'cherry'}

In [104]:
myset[0]

TypeError: 'set' object is not subscriptable

### Logic Operators

In [110]:
(1 > 2) and (2 < 3)

False

In [111]:
(1 > 2) or (2 < 3)

True

In [112]:
(1 == 2) or (2 == 3) or (4 == 4)

True

#### Statements

In [113]:
num4 = 388
num5 = 23
num6 = 56.6

In [115]:
#if statements
if num5 < 50:
    print('greater than 50!!!')

greater than 50!!!


In [117]:
# if-else statements
if num4 < 50:
    print('greater than 50!!!')
else:
    print('sorry, not greater than 50')

sorry, not greater than 50


In [120]:
# if-elif statement
if num4 > 50:
    print('greater than 50!!!')
elif num4 < 50:
    print('less than 50!!!')
else:
    print('equal to 50!')

greater than 50!!!


### For Loops

In [122]:
seq = [1,2,3,4,5]

for each_item in seq:
    print(each_item)

1
2
3
4
5


In [123]:
seq = [1,2,3,4,5]

for each_item in seq:
    print(each_item ** 2)

1
4
9
16
25


In [124]:
seq = [1,2,3,4,5]

for each_item in seq:
    print('Hello')

Hello
Hello
Hello
Hello
Hello


In [125]:
# While loops
i = 0 #initialization
while i < 6:    #Condition
    print(i)
    i = i+1     # i += 1

0
1
2
3
4
5


In [133]:
for item in range(0,12,2):
    print(item)

0
2
4
6
8
10


#### List Comprehension

In [134]:
x = [1,2,3,4]
out = []

for item in x:
    out.append(item ** 2)
out

[1, 4, 9, 16]

In [135]:
[item**2 for item in x]

[1, 4, 9, 16]

### Functions

In [139]:
def ave_score(name, math,eng,phy):
    average = (math + eng + phy) / 3
    return "{}'s average is {}".format(name, average)

In [140]:
ave_score('Kane',33,66,32)

"Kane's average is 43.666666666666664"

In [141]:
ave_score('obi', 77, 88, 99)

"obi's average is 88.0"

In [145]:
# Write a function to calculate the Body mass index of an individual and give approriate comments.

def BMI(weight_in_kg, height_in_m):
    """ Calculate person's body mass index 
    weight_in_kg: Person's weight
    height_in_m: person's height
    """
    
    bmi = weight_in_kg / height_in_m **2
    
    if bmi < 18.5:
        print('Your BMI is {}. You are underweight.'.format(bmi))
    elif bmi >= 18.5 and bmi <= 24.9:
        print('Your BMI is {}. You are Normal weight.'.format(bmi))
    elif bmi >= 25 and bmi <= 29:
        print('Your BMI is {}. You are Overweight.'.format(bmi))
    else:
        print('Your BMI is {}. You are Obese.'.format(bmi))

#### Input()

In [144]:
name = input('Enter your name: ')
name

Enter your name: Mary


'Mary'

## Numpy

In [146]:
# !pip install numpy
import numpy as np

In [147]:
my_list = [1,2,3]

In [148]:
np.array(my_list)

array([1, 2, 3])

In [149]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [150]:
#numpy methods
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [151]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [153]:
np.zeros(13)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [154]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [155]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [157]:
np.linspace(0,10,10)

array([ 0.        ,  1.11111111,  2.22222222,  3.33333333,  4.44444444,
        5.55555556,  6.66666667,  7.77777778,  8.88888889, 10.        ])

In [159]:
# Create an array of the given shape and populate it with random samples from a uniform distribution over [0, 1).
np.random.rand(2,5)

array([[0.23489098, 0.71363   , 0.44265922, 0.53605923, 0.22345501],
       [0.3877243 , 0.86903195, 0.4767865 , 0.80153256, 0.13438764]])

In [160]:
np.random.randn(5,5)

array([[-1.68413347, -0.6248895 , -1.55455932,  0.39984898, -0.50706476],
       [-1.59281428,  0.5510216 ,  0.27344238,  1.14734439,  0.39015205],
       [ 0.25009392, -0.01242163,  1.41039809,  1.2540988 , -0.3021958 ],
       [-1.31263602, -1.42023614,  1.28632907,  0.91012883,  0.14704097],
       [-0.22473329, -0.02591011,  0.89695906,  0.71773853, -0.51990163]])

In [166]:
np.random.randint(1,100,10)

array([27, 45, 79, 71, 48, 15, 81, 51, 65, 87])

In [179]:
arr = np.arange(20)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [181]:
arr.shape

(20,)

In [182]:
arr.reshape(10,2)

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15],
       [16, 17],
       [18, 19]])

In [183]:
arr.shape

(20,)

In [175]:
arr.max()

19

In [176]:
arr.min()

0

In [178]:
arr.shape

(20,)

#### Indexing arrays

In [184]:
arr_2d = np.array(([5,10,15],[20,25,30],[35,40,45]))

#Show
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [186]:
arr_2d[0] #first row

array([ 5, 10, 15])

In [187]:
arr_2d[1:]

array([[20, 25, 30],
       [35, 40, 45]])

In [189]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [191]:
arr_2d[1:, 1]

array([25, 40])

In [192]:
arr_2d[1:3, 1:3]

array([[25, 30],
       [40, 45]])

In [194]:
arr_2d[0, 1:]

array([10, 15])

In [195]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [196]:
arr_2d > 17

array([[False, False, False],
       [ True,  True,  True],
       [ True,  True,  True]])

In [200]:
arr_2d[arr_2d > 17] #Boolean indexing

array([20, 25, 30, 35, 40, 45])

### Pandas Series

In [201]:
import pandas as pd

In [208]:
labels = ['a','b','c']

my_list = [10,20,30]
arr = np.array([10,20,30])
d = {'a':10,'b':20,'c':30}

In [203]:
pd.Series(my_list)

0    10
1    20
2    30
dtype: int64

In [204]:
pd.Series(arr)

0    10
1    20
2    30
dtype: int32

In [206]:
pd.Series(data=d)

a    10
b    20
c    30
dtype: int64

In [207]:
pd.Series(my_list, index=['a','b', 'c'])

a    10
b    20
c    30
dtype: int64

In [209]:
pd.Series(arr, index=labels)

a    10
b    20
c    30
dtype: int32

In [210]:
ser1 = pd.Series([1,2,3,4],index = ['USA', 'Germany','USSR', 'Japan']) 
ser2 = pd.Series([1,2,5,4],index = ['USA', 'Germany','Italy', 'Japan'])                                   

In [211]:
ser1

USA        1
Germany    2
USSR       3
Japan      4
dtype: int64

In [212]:
ser2

USA        1
Germany    2
Italy      5
Japan      4
dtype: int64

In [213]:
ser1 + ser2

Germany    4.0
Italy      NaN
Japan      8.0
USA        2.0
USSR       NaN
dtype: float64

#### DataFrame

In [248]:
from numpy.random import randn
np.random.seed(42)

df = pd.DataFrame(randn(5,4), index=['A','B','C','D','E'], columns = 'W X Y Z'.split())

In [249]:
df

W         X         Y         Z
A  0.496714 -0.138264  0.647689  1.523030
B -0.234153 -0.234137  1.579213  0.767435
C -0.469474  0.542560 -0.463418 -0.465730
D  0.241962 -1.913280 -1.724918 -0.562288
E -1.012831  0.314247 -0.908024 -1.412304

## Selection and Indexing

Let's learn the various methods to grab data from a DataFrame

In [250]:
df.W

A    0.496714
B   -0.234153
C   -0.469474
D    0.241962
E   -1.012831
Name: W, dtype: float64

In [251]:
df['X']

A   -0.138264
B   -0.234137
C    0.542560
D   -1.913280
E    0.314247
Name: X, dtype: float64

In [253]:
type(df['X'])

pandas.core.series.Series

In [252]:
df[['X','Z']]

X         Z
A -0.138264  1.523030
B -0.234137  0.767435
C  0.542560 -0.465730
D -1.913280 -0.562288
E  0.314247 -1.412304

In [254]:
df

W         X         Y         Z
A  0.496714 -0.138264  0.647689  1.523030
B -0.234153 -0.234137  1.579213  0.767435
C -0.469474  0.542560 -0.463418 -0.465730
D  0.241962 -1.913280 -1.724918 -0.562288
E -1.012831  0.314247 -0.908024 -1.412304

In [255]:
df['new'] = df['W'] + df['Y']

In [256]:
df

W         X         Y         Z       new
A  0.496714 -0.138264  0.647689  1.523030  1.144403
B -0.234153 -0.234137  1.579213  0.767435  1.345059
C -0.469474  0.542560 -0.463418 -0.465730 -0.932892
D  0.241962 -1.913280 -1.724918 -0.562288 -1.482956
E -1.012831  0.314247 -0.908024 -1.412304 -1.920855

In [258]:
df.drop('new', axis=1)

W         X         Y         Z
A  0.496714 -0.138264  0.647689  1.523030
B -0.234153 -0.234137  1.579213  0.767435
C -0.469474  0.542560 -0.463418 -0.465730
D  0.241962 -1.913280 -1.724918 -0.562288
E -1.012831  0.314247 -0.908024 -1.412304

In [259]:
df

W         X         Y         Z       new
A  0.496714 -0.138264  0.647689  1.523030  1.144403
B -0.234153 -0.234137  1.579213  0.767435  1.345059
C -0.469474  0.542560 -0.463418 -0.465730 -0.932892
D  0.241962 -1.913280 -1.724918 -0.562288 -1.482956
E -1.012831  0.314247 -0.908024 -1.412304 -1.920855

In [260]:
df.drop('new', axis=1, inplace=True)

In [261]:
df

W         X         Y         Z
A  0.496714 -0.138264  0.647689  1.523030
B -0.234153 -0.234137  1.579213  0.767435
C -0.469474  0.542560 -0.463418 -0.465730
D  0.241962 -1.913280 -1.724918 -0.562288
E -1.012831  0.314247 -0.908024 -1.412304

In [262]:
#Selecting Rows using .loc and .iloc
df.loc['A']

W    0.496714
X   -0.138264
Y    0.647689
Z    1.523030
Name: A, dtype: float64

In [263]:
df.loc[cc]

W         X         Y         Z
A  0.496714 -0.138264  0.647689  1.523030
E -1.012831  0.314247 -0.908024 -1.412304

In [267]:
df.loc[['D', 'B'], ['Y', 'W']]

Y         W
D -1.724918  0.241962
B  1.579213 -0.234153

In [266]:
df.loc[['A', 'C'], 'Y']

A    0.647689
C   -0.463418
Name: Y, dtype: float64

In [264]:
df.iloc[0] #Same as df.loc['A']

W    0.496714
X   -0.138264
Y    0.647689
Z    1.523030
Name: A, dtype: float64

In [269]:
df

W         X         Y         Z
A  0.496714 -0.138264  0.647689  1.523030
B -0.234153 -0.234137  1.579213  0.767435
C -0.469474  0.542560 -0.463418 -0.465730
D  0.241962 -1.913280 -1.724918 -0.562288
E -1.012831  0.314247 -0.908024 -1.412304

In [268]:
df.iloc[0,1]

-0.13826430117118466

In [270]:
df.iloc[2,2]

-0.46341769281246226

In [271]:
df.loc['C', 'Y']

-0.46341769281246226

In [272]:
df

W         X         Y         Z
A  0.496714 -0.138264  0.647689  1.523030
B -0.234153 -0.234137  1.579213  0.767435
C -0.469474  0.542560 -0.463418 -0.465730
D  0.241962 -1.913280 -1.724918 -0.562288
E -1.012831  0.314247 -0.908024 -1.412304

In [273]:
#Boolean indexing or Conditional selection
df > 0

W      X      Y      Z
A   True  False   True   True
B  False  False   True   True
C  False   True  False  False
D   True  False  False  False
E  False   True  False  False

In [274]:
df[df > 0]

W         X         Y         Z
A  0.496714       NaN  0.647689  1.523030
B       NaN       NaN  1.579213  0.767435
C       NaN  0.542560       NaN       NaN
D  0.241962       NaN       NaN       NaN
E       NaN  0.314247       NaN       NaN

In [275]:
df

W         X         Y         Z
A  0.496714 -0.138264  0.647689  1.523030
B -0.234153 -0.234137  1.579213  0.767435
C -0.469474  0.542560 -0.463418 -0.465730
D  0.241962 -1.913280 -1.724918 -0.562288
E -1.012831  0.314247 -0.908024 -1.412304

In [276]:
df['W'] > 0

A     True
B    False
C    False
D     True
E    False
Name: W, dtype: bool

In [277]:
df[df['W'] > 0]

W         X         Y         Z
A  0.496714 -0.138264  0.647689  1.523030
D  0.241962 -1.913280 -1.724918 -0.562288

In [280]:
df[df['W'] > 0]['X']

A   -0.138264
D   -1.913280
Name: X, dtype: float64

In [281]:
type(df[df['W'] > 0]['X'])

pandas.core.series.Series

In [282]:
df

W         X         Y         Z
A  0.496714 -0.138264  0.647689  1.523030
B -0.234153 -0.234137  1.579213  0.767435
C -0.469474  0.542560 -0.463418 -0.465730
D  0.241962 -1.913280 -1.724918 -0.562288
E -1.012831  0.314247 -0.908024 -1.412304

In [283]:
df>0

W      X      Y      Z
A   True  False   True   True
B  False  False   True   True
C  False   True  False  False
D   True  False  False  False
E  False   True  False  False

In [284]:
df[df>0]

W         X         Y         Z
A  0.496714       NaN  0.647689  1.523030
B       NaN       NaN  1.579213  0.767435
C       NaN  0.542560       NaN       NaN
D  0.241962       NaN       NaN       NaN
E       NaN  0.314247       NaN       NaN

In [285]:
df

W         X         Y         Z
A  0.496714 -0.138264  0.647689  1.523030
B -0.234153 -0.234137  1.579213  0.767435
C -0.469474  0.542560 -0.463418 -0.465730
D  0.241962 -1.913280 -1.724918 -0.562288
E -1.012831  0.314247 -0.908024 -1.412304

In [286]:
df['X'] < 0

A     True
B     True
C    False
D     True
E    False
Name: X, dtype: bool

In [288]:
df[df['X'] < 0][['Y','Z']]

Y         Z
A  0.647689  1.523030
B  1.579213  0.767435
D -1.724918 -0.562288

In [289]:
df

W         X         Y         Z
A  0.496714 -0.138264  0.647689  1.523030
B -0.234153 -0.234137  1.579213  0.767435
C -0.469474  0.542560 -0.463418 -0.465730
D  0.241962 -1.913280 -1.724918 -0.562288
E -1.012831  0.314247 -0.908024 -1.412304

In [294]:
df[(df['W'] < 0) & (df['Y'] > 0)]

W         X         Y         Z
B -0.234153 -0.234137  1.579213  0.767435

In [295]:
df[(df['W'] < 0) | (df['Y'] > 0)]

W         X         Y         Z
A  0.496714 -0.138264  0.647689  1.523030
B -0.234153 -0.234137  1.579213  0.767435
C -0.469474  0.542560 -0.463418 -0.465730
E -1.012831  0.314247 -0.908024 -1.412304