### Numpy

### Install numpy library

!pip install numpy

In [1]:
import numpy as np

In [2]:
my_list = [1, 2, 3]

In [3]:
np.array(my_list)

array([1, 2, 3])

In [4]:
my_matrix = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

### Numpy methods

In [6]:
np.arange(0, 10) #list out an array of the range

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

In [8]:
np.zeros(8)

array([0., 0., 0., 0., 0., 0., 0., 0.])

In [10]:
np.zeros((5, 5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [11]:
np.ones((3, 3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [12]:
np.linspace(0, 10, 10)

array([ 0.        ,  1.11111111,  2.22222222,  3.33333333,  4.44444444,
        5.55555556,  6.66666667,  7.77777778,  8.88888889, 10.        ])

In [13]:
np.random.rand(2)

array([0.72348745, 0.68419532])

In [14]:
np.random.randn(5)

array([ 1.15519196, -0.40411205,  0.95485177, -1.23048734, -0.46356909])

In [15]:
np.random.randn(5, 5)

array([[-0.34465764,  0.63753277, -1.04901579, -1.05879688,  0.48664696],
       [-0.54058321,  0.34768813, -0.74872043, -0.37196619, -0.1521321 ],
       [-0.85064919, -0.28071019,  0.23063569,  0.35412625, -1.18023331],
       [ 1.36208709,  1.5296858 ,  1.07817736,  0.0538859 ,  1.59524577],
       [-1.79488402,  0.43852352, -0.85894347, -0.80748144, -0.13895427]])

In [16]:
np.random.randint(1, 100, 10)

array([17, 19, 45, 28, 94, 10, 77, 28,  2, 40])

In [19]:
arr = np.arange(20)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [21]:
arr.reshape(10,2)

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15],
       [16, 17],
       [18, 19]])

In [22]:
arr.reshape(5, 4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [23]:
arr.max()

19

In [26]:
arr.min()

0

In [27]:
arr.shape()

TypeError: 'tuple' object is not callable

In [28]:
#arr_2d = 

### Pandas

### Pandas Installation

!pip install pandas

In [29]:
import pandas as pd

### Pandas Series

In [31]:
my_list =  [10, 20, 30]
arr = np.array([10, 20, 30])
d = {'a': 10, 'b': 20, 'c': 30}

In [32]:
pd.Series(my_list)

0    10
1    20
2    30
dtype: int64

In [33]:
pd.Series(arr)

0    10
1    20
2    30
dtype: int32

In [34]:
pd.Series(d)

a    10
b    20
c    30
dtype: int64

In [35]:
pd.Series(my_list, index=['a', 'b', 'c'])

a    10
b    20
c    30
dtype: int64

In [36]:
labels = ['a', 'b', 'c']

In [37]:
pd.Series(my_list, index = labels)

a    10
b    20
c    30
dtype: int64

In [38]:
ser1 = pd.Series([1,2,3,4],index = ['USA', 'Germany','USSR', 'Japan']) 
ser2 = pd.Series([1,2,5,4],index = ['USA', 'Germany','Italy', 'Japan'])

In [39]:
ser1

USA        1
Germany    2
USSR       3
Japan      4
dtype: int64

In [40]:
ser1 + ser2

Germany    4.0
Italy      NaN
Japan      8.0
USA        2.0
USSR       NaN
dtype: float64

### Pandas DataFrame

In [41]:
from numpy.random import randn

In [42]:
df = pd.DataFrame(randn(5, 4), index = ['A', 'B', 'C', 'D', 'E'])

In [43]:
df

0         1         2         3
A  0.667439 -0.190819  1.215491  2.208101
B  1.380610 -0.284425 -0.365174 -1.282426
C  0.067599  0.569434  1.988794 -1.604973
D -0.656660 -0.876892 -0.475156  1.105338
E  0.493472 -1.112836  0.737439  0.206505

In [51]:
df = pd.DataFrame(randn(5, 4), index = ['A', 'B', 'C', 'D', 'E'], columns = 'W X Y Z'.split())

In [52]:
df

W         X         Y         Z
A  1.465649 -0.225776  0.067528 -1.424748
B -0.544383  0.110923 -1.150994  0.375698
C -0.600639 -0.291694 -0.601707  1.852278
D -0.013497 -1.057711  0.822545 -1.220844
E  0.208864 -1.959670 -1.328186  0.196861

In [53]:
df

W         X         Y         Z
A  1.465649 -0.225776  0.067528 -1.424748
B -0.544383  0.110923 -1.150994  0.375698
C -0.600639 -0.291694 -0.601707  1.852278
D -0.013497 -1.057711  0.822545 -1.220844
E  0.208864 -1.959670 -1.328186  0.196861

In [54]:
# random.seed helps to keep random numbers in place

from numpy.random import randn
np.random.seed(42)

df = pd.DataFrame(randn(5,4), index = 'A B C D E'.split(), columns = 'W X Y Z'.split())

In [55]:
df

W         X         Y         Z
A  0.496714 -0.138264  0.647689  1.523030
B -0.234153 -0.234137  1.579213  0.767435
C -0.469474  0.542560 -0.463418 -0.465730
D  0.241962 -1.913280 -1.724918 -0.562288
E -1.012831  0.314247 -0.908024 -1.412304

In [56]:
df

W         X         Y         Z
A  0.496714 -0.138264  0.647689  1.523030
B -0.234153 -0.234137  1.579213  0.767435
C -0.469474  0.542560 -0.463418 -0.465730
D  0.241962 -1.913280 -1.724918 -0.562288
E -1.012831  0.314247 -0.908024 -1.412304

### Selecting and Indexing

In [62]:
df['X']

A   -0.138264
B   -0.234137
C    0.542560
D   -1.913280
E    0.314247
Name: X, dtype: float64

In [63]:
#df['X'].type()

AttributeError: 'Series' object has no attribute 'type'

In [64]:
df[['X', 'Z']]

X         Z
A -0.138264  1.523030
B -0.234137  0.767435
C  0.542560 -0.465730
D -1.913280 -0.562288
E  0.314247 -1.412304

In [65]:
df['new'] = df['W'] + df['X']

In [66]:
df

W         X         Y         Z       new
A  0.496714 -0.138264  0.647689  1.523030  0.358450
B -0.234153 -0.234137  1.579213  0.767435 -0.468290
C -0.469474  0.542560 -0.463418 -0.465730  0.073086
D  0.241962 -1.913280 -1.724918 -0.562288 -1.671318
E -1.012831  0.314247 -0.908024 -1.412304 -0.698584

In [67]:
df.drop('new', axis = 1)

W         X         Y         Z
A  0.496714 -0.138264  0.647689  1.523030
B -0.234153 -0.234137  1.579213  0.767435
C -0.469474  0.542560 -0.463418 -0.465730
D  0.241962 -1.913280 -1.724918 -0.562288
E -1.012831  0.314247 -0.908024 -1.412304

In [68]:
df

W         X         Y         Z       new
A  0.496714 -0.138264  0.647689  1.523030  0.358450
B -0.234153 -0.234137  1.579213  0.767435 -0.468290
C -0.469474  0.542560 -0.463418 -0.465730  0.073086
D  0.241962 -1.913280 -1.724918 -0.562288 -1.671318
E -1.012831  0.314247 -0.908024 -1.412304 -0.698584

In [69]:
df.drop('new', axis = 1, inplace=True)

In [70]:
df

W         X         Y         Z
A  0.496714 -0.138264  0.647689  1.523030
B -0.234153 -0.234137  1.579213  0.767435
C -0.469474  0.542560 -0.463418 -0.465730
D  0.241962 -1.913280 -1.724918 -0.562288
E -1.012831  0.314247 -0.908024 -1.412304

In [71]:
(df['W'] < 0) & (df['Y'] > 0)

A    False
B     True
C    False
D    False
E    False
dtype: bool

In [72]:
df[(df['W'] < 0) & (df['Y'] > 0)]

W         X         Y         Z
B -0.234153 -0.234137  1.579213  0.767435